In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("COVID-19_Reported_Patient_Impact_and_Hospital_Capacity_by_State_Timeseries.csv")

In [3]:
df

,state,date,critical_staffing_shortage_today_yes,critical_staffing_shortage_today_no,critical_staffing_shortage_today_not_reported,critical_staffing_shortage_anticipated_within_week_yes,critical_staffing_shortage_anticipated_within_week_no,critical_staffing_shortage_anticipated_within_week_not_reported,hospital_onset_covid,hospital_onset_covid_coverage,...,previous_day_admission_pediatric_covid_confirmed_5_11,previous_day_admission_pediatric_covid_confirmed_5_11_coverage,previous_day_admission_pediatric_covid_confirmed_unknown,previous_day_admission_pediatric_covid_confirmed_unknown_coverage,staffed_icu_pediatric_patients_confirmed_covid,staffed_icu_pediatric_patients_confirmed_covid_coverage,staffed_pediatric_icu_bed_occupancy,staffed_pediatric_icu_bed_occupancy_coverage,total_staffed_pediatric_icu_beds,total_staffed_pediatric_icu_beds_coverage
0,VI,2020/10/17,1,1,0,2,0,0,0.0,2,...,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0
1,VT,2020/10/16,1,15,1,1,15,1,0.0,16,...,NaN,0,NaN,0,0.0,1,19.0,1,33.0,1
2,RI,2020/10/15,2,12,1,2,12,1,4.0,14,...,NaN,0,NaN,0,0.0,3,0.0,3,0.0,3
3,RI,2020/10/14,2,12,1,2,12,1,4.0,14,...,NaN,0,NaN,0,0.0,3,0.0,3,0.0,3
4,VI,2020/10/13,1,1,0,2,0,0,0.0,2,...,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42288,ID,2021/03/21,3,41,8,3,41,8,1.0,51,...,NaN,0,NaN,0,NaN,0,84.0,35,229.0,35
42289,IN,2020/02/14,0,0,1,0,0,1,0.0,1,...,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0
42290,TX,2020/02/22,0,0,3,0,0,3,0.0,1,...,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0
42291,GA,2021/02/15,39,102,14,44,96,15,30.0,152,...,NaN,0,NaN,0,NaN,0,122.0,73,239.0,73
42292,MD,2020/12/15,7,44,1,10,41,1,14.0,51,...,NaN,0,NaN,0,NaN,0,179.0,51,238.0,51

In [5]:
df_tx = df[df["state"] == "TX"]

In [6]:
df_tx

,state,date,critical_staffing_shortage_today_yes,critical_staffing_shortage_today_no,critical_staffing_shortage_today_not_reported,critical_staffing_shortage_anticipated_within_week_yes,critical_staffing_shortage_anticipated_within_week_no,critical_staffing_shortage_anticipated_within_week_not_reported,hospital_onset_covid,hospital_onset_covid_coverage,...,previous_day_admission_pediatric_covid_confirmed_5_11,previous_day_admission_pediatric_covid_confirmed_5_11_coverage,previous_day_admission_pediatric_covid_confirmed_unknown,previous_day_admission_pediatric_covid_confirmed_unknown_coverage,staffed_icu_pediatric_patients_confirmed_covid,staffed_icu_pediatric_patients_confirmed_covid_coverage,staffed_pediatric_icu_bed_occupancy,staffed_pediatric_icu_bed_occupancy_coverage,total_staffed_pediatric_icu_beds,total_staffed_pediatric_icu_beds_coverage
428,TX,2020/10/21,108,472,5,128,452,5,108.0,580,...,NaN,0,NaN,0,0.0,4,289.0,35,217.0,35
450,TX,2020/07/16,71,115,295,80,97,304,127.0,360,...,NaN,0,NaN,0,41.0,227,1303.0,191,1571.0,169
451,TX,2020/05/26,0,0,380,0,0,380,31.0,345,...,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0
454,TX,2020/08/08,118,323,105,143,290,113,120.0,536,...,NaN,0,NaN,0,12.0,48,281.0,50,198.0,44
505,TX,2020/05/23,0,0,381,0,0,381,18.0,348,...,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42016,TX,2020/02/10,0,0,1,0,0,1,NaN,0,...,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0
42117,TX,2020/01/06,0,0,2,0,0,2,0.0,1,...,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0
42168,TX,2020/02/06,0,0,1,0,0,1,NaN,0,...,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0
42260,TX,2020/01/09,0,0,2,0,0,2,0.0,1,...,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0
42290,TX,2020/02/22,0,0,3,0,0,3,0.0,1,...,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0